package com.ahmetkaragunlu.financeai.screens.auth

enum class AuthState {
    EMPTY,
    SUCCESS,
    FAILURE,
    USER_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    INVALID_EMAIL_OR_PASSWORD,
    USER_NOT_REGISTERED,
    ID_TOKEN_IS_NULL,
    INVALID_OOB_CODE,
    EMAIL_VERIFICATION_SENT,
    EMAIL_NOT_VERIFIED
}